# .github/workflows/deploy-calculator.yml
name: Deploy Calculator

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Deploy Calculator
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Calculator  # The folder for the Calculator project
          destination_dir: calculator  # Subdirectory on GitHub Pages
